baseURL: http://cashpw.com/
enableEmoji: true
enableRobotsTXT: true
languageCode: en-us
theme: hugo-tufte
title: Cash Prokop-Weaver
#
minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  # hugo-tufte
  # showPoweredBy: true
  alwaysShowToc: true
  showPostsOnHome: "list"
  hideAuthor: true
  mainSections: ["posts"]
  includeMathWhenNeeded: true
  toc: true
  hideTags: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: catppuccin-macchiato
